const nickNamesArray = [
		"Wolf",
		"Monster",
		"Noob",
		"Ботяра",
		"Киборг228",
		"Нагибатор",
		"Нагибатор228",
		"Бот228",
		"Пасхалка",
		"Player",
		"Макс",
		"Никитка",
		"Читер777",
		"Влад",
		"Алв дай ID",
		"Продам гараж",
		"Cheater",
		"НеАлвен",
		"NotAlven",
		"БанЧитерам",
		"Бан",
		"Луна",
		"НикиткаНуп",
		"Нуб123",
		"Noob777",
        "twitterboy",
        "Cash choppa",
        "БАЗЗИКС tali",
        "lil Shev",
        "ArtPtz",
        "Lil_rayzik",
        "HANTLEYS",
        "lil Xanex",
        "nickolas",
        "bullys",
        "Big Niko",
        "lil freat",
        "RRYAN",
        "triplefake",
        "Insulter",
        "JeryL",
        "Pulito",
        "Danki",
        "YEKK180",
        "Holar",
        "MC Nells",
        "Slvme Gugio",
        "mbo SouthPaw",
        "Marijan",
        "Annakonda",
        "Narkoekho",
        "OG Livan",
        "McPleh",
        "5.R.S.H T",
        "OMMY NINETAN",
        "Drummatix",
        "Ser Go",
        "Gluko",
        "Sayp",
        "NEKEEY",
        "SashaSLIME",
        "METZ INTAET",
        "Аннаконда",
        "Fendam",
        "命HasBelKader運",
        "m3an",
        "+=(BOR)MIKC=+",
        "Хейтер",
        "Уиджи",
        "6lock 6abby",
        "M.A.V",
        "SOFCUSOM",
        "Weegee",
        "ason_Berner",
        "LordTwoAndZero",
        "Xx-Eiter",
        "WALL-E",
        "Rassveт",
        "Great PALAMAL",
        "|John Ye$eff|",
        "Sequn",
        "AnalniyPirat",
        "zZzZ",
        "ebash v kashy",
        "Ceresida",
        "Snowman",
        "Robin Taylor",
        "BlackWolf",
        "crazy",
        "Anagamand",
        "RobbaN ha aimbat!",
        "KenWrot",
        "Ken",
        "Perius",
        "MrBananaHeaded",
        "Black_Swan",
        "Vooolume",
        "Gashtet",
        "ПОДРОБНЕЕ",
        "Kelas",
        "ShilS",
        "Smiley",
        "Shadowredeemer",
        "JokeR1796",
        "Anaginn",
        "Black_Metal_Ist_Krieg",
        "Perezzz",
        "hot",
        "Perilhala",
        "steyntjeee",
        "Popka",
        "bass",
        "Black_Jack",
        "Kell_kull",
        "MASTER.",
        "Xakep",
        "Gashura",
        "BlackTiger > Avana-Pro*)",
        "Kel’T",
        "Joker12",
        "Shadowbeard",
        "Zathe",
        "Waleron;D",
        "Perez___",
        "Razor",
        "Независимый",
        "PerCik",
        "ZeTLorD",
        "Shadowbreaker",
        "dizze",
        "Cerelv",
        "yTka:D",
        "ShadowTr",
        "Pickles",
        "MrArseniy",
        "MrAnfaini",
        "Gasperini",
        "Skinchik",
        "Zadrot",
        "RobinHood",
        "RoarCreaToR",
        "Kelmoff^^",
        "Кресло",
        "BlackSea*",
        "Shadowbourne",
        "Голубь",
        "jeka",
        "Peririel",
        "RobertDillDanger",
        "Anage 1",
        "Cerus",
        "Perindis",
        "_.**__**",
        "моZг",
        "lololosha",
        "TheSuspect",
        "Ceresius",
        "MrAnonims",
        "Pergament 1",
        "Perfect paradise",
        "Anakelv",
        "ZXMAXZ",
        "Tank",
        "R.V.A. [khv]",
        "Skype",
        "Pepper",
        "Zeus",
        "Robertos",
        "Black_Hanter",
        "Roberto",
        "Anakus",
        "Riko*",
        "TheStrikeR",
        "Black_Star",
        "Cervin",
        "Kellye",
        "MrBanana",
        "Shady Lady",
        "Joker_KZ",
        "Shadrak_Grifer",
        "Kelley",
        "Gasoline",
        "S7.RU",
        "Gary Young",
        "TheTrix",
        "моZг -2",
        "RobiN",
        "Gashishik",
        "devl3d:DDDD",
        "killer^^)",
        "Periris",
        "pavlik",
        "Scorpion",
        "Zool",
        "Kelelore",
        "Anage",
        "TopFive",
        "AXEEKOZ",
        "Joker+++",
        "Mr7ech",
        "Black_Hawk_Down",
        "ShadowProsTo",
        "potato",
        "RobOMan",
        "Свин",
        "BlackRock",
        "Shadowmoon",
        "Kelerana",
        "Smoothy",
        "Pro(kilss)",
        "Mr?KuP9#15",
        "Cervel_Knight",
        "Anaenthe",
        "Винл",
        "Kelegamand",
        "Cerdana",
        "Shady",
        "Pika4uGR",
        "RobertMer",
        "TheWhiteOverlord",
        "York",
        "Rio",
        "Winston",
        "Kelehelm",
        "TheStorey™",
        "PerfectBro",
        "KellMe",
        "Kelenin",
        "BlackWolf 1",
        "Analanim",
        "Pyc9na",
        "KenT — DJProduction",
        "KenT[XD]*",
        "MrAsasIn",
        "Perith",
        "Kemath",
        "golish",
        "Persik_YTM",
        "MrAxel",
        "pussy destroyer",
        "RobaRoba:3",
        "Twister",
        "Gasson",
        "oIITiMicT",
        "TheTwo",
        "cruel",
        "Robobolt",
        "ghost004 //SWAG",
        "Shadowfist",
        "ПОДРОБНЕЕ",
        "Quine",
        "Rebels",
        "klubni4k@",
        "Wimoway",
        "Perirdana",
        "kebabcik",
        "Mr>KiT_KaT",
        "Shadow_Wariror",
        "Garufi",
        "Psix",
        "Gashakar",
        "SwEg",
        "lusky-Мистер везунчик",
        "mons",
        "Paxom",
        "Smychok",
        "Ppoper",
        "Black_Angel",
        "AXE|НИК|cl—DOC—",
        "TheSkorpion",
        "STRONS",
        "Jojoamanu",
        "White™",
        "Anadwyn",
        "AWP|",
        "Volshebnik",
        "AnalFluteH",
        "Zhenya",
        "Roxas",
        "Wolf",
        "Kelelas",
        "Roberta_Costa",
        "Perongafa",
        "Pumba",
        "Joker OnlyDrive",
        "Perirne",
        "BlackTea",
        "XotDog[ГОМЕЛЬ]",
        "Robles for me :*",
        "BlackSad 1",
        "Kelelv",
        "BlackStar",
        "Shadows",
        "lucky-Мистер",
        "ПОДРОБНЕЕ",
        "Peridor",
        "ПОДРОБНЕЕ",
        "Pumpkin",
        "BlackSkif",
        "BlackShark",
        "KenTJo",
        "rezhuzal",
        "Garvel",
        "YouTuber",
        "Kellee",
        "AXIFUWIR",
        "_Wet_Willie",
        "Jointu",
        "V-I-M-A-K",
        "Robotics",
        "Anahuginn",
        "Joker -EZ-",
        "Black_Pr(o)",
        "Black_Jack777",
        "Cerezar",
        "Black_Hard",
        "Joker_F",
        "Vorchun",
        "TheTigerPlay",
        "Kemper_17 rus",
        "Sniр[E]r",
        "Ozil",
        "Kelerius",
        "Perinin",
        "Random4ik",
        "TheTheLoWcss1337man",
        "Tony Award",
        "Terebon’ka C:",
        "Shadrian",
        "TheTrollingRage",
        "ПеLьМЕshKa",
        "Shadowness",
        "Zadrot-Rozhok",
        "SHOP.GADGETUFA.RU",
        "Perfect_Om$k",
        "TapakaH",
        "TheVolturi",
        "TheVladBro",
        "XaXaTyH",
        "V@reny",
        "Snaiper PRO",
        "Persi Kryz",
        "MrBening",
        "Cerin",
        "Kelbine",
        "Perfect [186_rus]",
        "max",
        "Perfectly user",
        "Joker",
        "Cererana",
        "_Winky)",
        "Ceregamand",
        "Panda",
        "TheTeoGuy;3",
        "Jokerit",
        "Perilen",
        "Winnerman[CWS]",
        "TrollFace™",
        "AWP~Mr.Pitbull",
        "sKiLz_BLR",
        "kazakh",
        "TheSushkaMen",
        "Kekus",
        "Shadow™",
        "AXEllen",
        "Shadowchaser",
        "Xauzenberg",
        "Smyley",
        "Shadow_JonyKEM",
        "Cerelbine",
        "Kelchner",
        "Kelm",
        "VaaS",
        "P0n41k",
        "AWPmAsTeRLoLHD:D",
        "Robert69",
        "Postmen",
        "Perfoman",
        "Kelmeena",
        "SmO_oke",
        "BlackMoney",
        "Weezy",
        "Shadow_angel",
        "Monster.",
        "ShadowPeople",
        "Perigamand",
        "Joker-Men",
        "Shadowbrew",
        "Shaera",
        "Kemper228",
        "Kelegelv",
        "Segdugasz",
        "Ceroelyu",
        "TheTerAn",
        "TigrTOP",
        "AXE|НИК|—KAMAR—",
        "Anall-_-Karnavall",
        "AWP_Pro Kartinpo {Mr.}Kill’s Ma",
        "Cereswyn",
        "BlackMoon",
        "Ceremand",
        "Perfec",
        "Anadi",
        "Zadrot__________",
        "Black_Niger",
        "Perfect",
        "uJImup4ik",
        "Garus",
        "Kelezel",
        "Sti",
        "Pechenka",
        "BlackOtmaz",
        "TraBa",
        "Jaline",
        "Девочка с характером",
        "ТеТя Махіто",
        "★ Sияние_zвездЫ ★",
        "Bloody Mary",
        "Ядовитая бабочка",
        "Чертовка",
        "*** К@пRизЮ/ьk@ ***",
        "МокРыЕ РесНичКи",
        "koweчка",
        "Olivaka",
        "Kateriska",
        "Terracotka",
        "Tilestra",
        "Лунный ангелочек",
        "Black girl",
        "chertOFFka",
        "l٥ﻻ ﻉ√٥υ♥",
        "Nurico",
        "Shady Lady",
        "-=B.E.S.=-",
        "Кpоша ShOCOLATKA",
        "Sweetums Talys",
        "И$ҜҏȺ Кокосик",
        "Mini_Cherry Vedmochka",
        "— CмЕтАНкА",
        "DIVA irisSska",
        "Sandra Ясно солнышко",
        "Lady in dreams в",
        "ожидании рая",
        "КаПрИзНаЯ ДеВокА",
        "ЧерныйЛифчик",
        "ღღღ Еще_не_любила ღღღ",
        "+Парапизована+",
        "vip…Осторожно БРЮНЕТКА…",
        "Saki",
        "Miss Priss",
        "Pit-Pit",
        "SIAMKA",
        "Joker4326223",
        "Kellyyy",
        "Борец",
        "Pers",
        "Олимпик",
        "PerfectVoid",
        "Kell",
        "TePeBoNbK12",
        "BlackWolf_09",
        "MrAssassinRus",
        "Gasner",
        "Black_Nickromant",
        "Cerne",
        "Perretti",
        "Tank2014",
        "Spartac.",
        "Anahelm",
        "S.C.R.E.A.M",
        "Joker7smile",
        "donny",
        "KenT_64rus)",
        "TheStolenSweetroll",
        "Kelebor",
        "BlackTheDeath",
        "TommyGame",
        "Kempac",
        "Gasius",
        "TheWildTurtle",
        "Vatson",
        "niki-koy joniboy",
        "Joker aim)",
        "TheSzturmowiecPL",
        "TeSla",
        "okkypay 14/88",
        "wHo",
        "Analigin",
        "Smychok.",
        "BlackSkorpion",
        "Gastik",
        "Persic",
        "TheTerAnH!k",
        "mentos"
    ];
	
export function getRandomNickName()
{
	return nickNamesArray[parseInt(Math.random() * nickNamesArray.length)];
}